### ISSUE TITLE
.uf2

### ISSUE THREAD

**Issue by Ptwhite** [marobi/Pico_6502_v4_ehbasic#1]
Hi - some great work - Im very new to all this -but I cant find UF2 file?????

**Comment by marobi** [comment]
Hi, look under ReleasesRienOn 30 Oct 2023, at 12:20, Ptwhite ***@***.***> wrote:﻿
Hi - some great work - Im very new to all this -but I cant find UF2 file?????

**Comment by Ptwhite** [comment]
Thanks for your help - 
Sorted = Can't believe I didnt see it ////
